#include <iostream>
using namespace std;
 
/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

**/

int main () {
   // Local variable declaration:
   int first = 1;
   int second = 2;
   int next = 0;
   int sum = 2;

   // while loop execution
   while( next < 4000000) {
        next = first + second;
        if(next%2 == 0) sum += next;
        first = second;
        second = next;
        
   }
   cout << sum;
 
   return 0;
}
